---
dirpath:
  proj_dir: /home/malay/pm25/pm2.5/
  data_dir: /hdd/malay/data/
  model_dir: /hdd/malay/models/
  plots_dir: /hdd/malay/plots/

filepath:
  pkl_fp: bihar_meteo_era5_may_april_iterative_imputed.pkl
  npy_fp: bihar_may_april.npy
  locations_fp: bihar_locations.txt
  map_fp: bihar.json

threshold:
  distance: 5
  haze: 100

dataset:
  update: 1
  data_start: [2023, 5, 1]
  data_end: [2024, 4, 30]

split:
  train_start: [2023, 5, 1]
  train_end: [2023, 12, 31]
  val_start: [2024, 1, 1]
  val_end: [2024, 2, 29]
  test_start: [2024, 3, 1]
  test_end: [2024, 4, 30]

meteo_var: ['timestamp', 'longitude', 'latitude', 'rh', 'temp', 'blh', 'kx', 'sp', 'tp', 'u10', 'v10', 'pm25']

train:
  batch_size: 128
  num_exp: 5
  num_epochs: 30
  forecast_len: 24
  hist_len: 48
  emb_dim: 8
  hid_dim: 32
  edge_dim: 5
  lr: 0.001
  attn: luong
  model: Attn_GNN_GRU