---
filepath:
  proj_dir: /home/malay/pm25/pm2.5/
  data_dir: /hdd/malay/
  model_dir: /models/
  plots_dir: /plots/
  data_fp: bihar_meteo_era5_may_jan_iterative_imputed.pkl
  locations_fp: locations.txt
  bihar_map_fp: bihar.json

train:
  batch_size: 4
  epochs: 10
  forecast_window: 12
  window_size: 600
  lr: 0.005

split:
  train_start: [[2023, 1, 1], GMT]
  train_end: [[2023, 12, 31], GMT]
  val_start: [[2024, 1, 1], GMT]
  val_end: [[2024, 1, 15], GMT]
  test_start: [[2024, 1, 16], GMT]
  test_end: [[2024, 1, 31], GMT]