base_dir = 'C:/Users/malay/OneDrive/Desktop/CSE/Thesis/pm2.5/'
data_dir = f'{base_dir}/data/'
data_bihar = f'{data_dir}/Bihar/'
bihar_data_419 = f'{data_bihar}/Bihar_419_data.pkl'
model_dir = f'{base_dir}/models/'
plot_dir = f'{base_dir}/plots/'
