base_dir = '/home/malay/pm25/pm2.5/'
data_dir = f'/hdd/malay'
data_bihar = f'{data_dir}/bihar'
bihar_data_419 = f'{data_bihar}/Bihar_419_data.pkl'
model_dir = f'{data_dir}/models/'
plot_dir = f'{data_dir}/plots'
bihar_plot_dir = f'{plot_dir}/bihar'
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
GRID_SIZE = 1000
AREA_BIHAR = 94163